// Generated by `modulato content` — do not edit. Regenerate after
// changing your content source.
// (Augments the module that DECLARES ModulatoContent — merging only works
// at the declaration site, not on re-exports.)
declare module 'modulato/config' {
  interface ModulatoContent {
    projects: {
      slug: string
      title: string
      year: number
      color: string
      image: string
      description: string
    }[]
  }
}

export {}
